<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>KumbiaPHP con Bootstrap</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="kumbiaphp.info">

        <?php Tag::css('bootstrap3/bootstrap.min') ?>
        <!--<?//php Tag::css('bootstrap/bootstrap-responsive.min') ?>-->
        <?php Tag::css('style') ?>
        <?php Tag::css('flash') ?>
        <?php echo Html::includeCss() ?>

        <!-- Le styles -->
        <!-- Le styles -->
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="http://foro.kumbiaphp.com/themes/kumbia/design/favicon.png" type="image/x-icon" />
    </head>

    <body> 
        <?php View::partial('sgc/navbar') ?>

        <div class="container">
            <?php View::content(); ?>
        </div> <!-- /container -->

        <?php View::partial('sgc/footer') ?>

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <?php echo Tag::js("jquery/jquery.kumbiaphp"); ?>
        <?php echo Tag::js("bootstrap3/bootstrap.min"); ?>

    </body>
</html>
