<!-- archivo /views/archivos/index.phtml -->




<?php View::notify(); ?>
<div class="container-fluid dw-shell-view">
    <?php View::process($page_module, $page_title, $set_title); ?>
    <br/>
    <?php echo DwForm::open('', 'post', array('id' => 'form', 
        'class' => 'dw-validate')); ?>

    <div class="row fileupload-buttonbar">

        <div class="span2">
            <span class="btn btn-success fileinput-button">
                <i class="icon-plus icon-white"></i>
                <span>Seleccionar Archivo</span>
                <input id="archivo" type="file" name="archivo" class="input-large">
            </span>
        </div>

        <div id="upload-progress" class="span4 fileupload-progress fade">
            <div class="progress progress-success progress-striped active" 
                 role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="bar" style="width:0%;"></div>
            </div>
        </div>

        

    </div>
    <?php echo DwForm::hidden('archivoUplod', NULL, 'default.png'); ?>
    <div class="row-fluid">
        <div class="form-actions">
            <?php echo DwButton::submit('subir') ?>
            <?php echo DwButton::reset('form'); ?>
            <?php echo DwButton::cancel(); ?>
        </div>
    </div>









    <!--
    <div class="row-fluid">
        <div class="span6">
    <?php
    echo DwForm::file('archivo', array('class' => 'input-xxlarge input-required'
        . ' show-error'), NULL, 'Ingrese un archivo .zip ó .rar:')
    ?>
    <?php echo DwForm::hidden('oculto', NULL, '1') //para saber si se envió el form ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="form-actions">
    <?php echo DwForm::submit('subir') ?>
    <?php echo DwButton::reset('form'); ?>
    <?php echo DwButton::cancel(); ?>
        </div>
    </div>
    <?php echo DwForm::close() ?>
    <br/>
    <br/>
    <h1>Subida de Imagen</h1>
    <?php echo Form::openMultipart('archivos/imagen') ?>
        Ingrese una imagen .jpg , .gif ó .png :
    <?php echo Form::file('archivo') ?>
    <?php echo Form::hidden('oculto', NULL, '1') //para saber si se envió el form ?>
    <?php echo Form::submit('subir') ?>
    <?php echo Form::close() ?>-->
</div>

<?php View::partial('jquery.file-upload'); ?>

<script type="text/javascript">
    $('#archivo').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sgc/archivos/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(pdf)$/i,
        start: function () {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger')
                    .addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width', progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
                    .done(function (result, textStatus, jqXHR) {
                        if (textStatus != 'success' || result.error != null) {
                            $('.bar').parent().removeClass('progress-success')
                            .addClass('progress-danger');
                            DwMessage('Oops! el archivo no se ha podido cargar. \n\
                                    <br />Detalle del error: ' 
                            + (result.error != null) ? result.error : textStatus);
                        } else {
                            DwMessage('El archivo se ha cargado correctamente!', 'success');
                            $("#archivoUplod").val(result.name);
                            //$("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/' + result.name);
                            DwPopupReport('<?php echo PUBLIC_PATH; ?>files/sgc/' + result.name);
                        }
                    })
                    .fail(function (jqXHR, textStatus, errorThrown) {
                        if (textStatus != null) {
                            DwMessage('Oops! el archivo no se ha podido cargar. \
                                        <br />Detalle del error: ' + textStatus);
                            $('.bar').parent().removeClass('progress-success')
                                    .addClass('progress-danger');
                            setTimeout(function () {
                                $('#upload-progress').addClass('fade');
                            }, 1000);
                        } else {
                            DwMessage('Oops! al parecer el archivo no es una extensión valida. <br />Intenta con otro archivo.');
                            $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                            $('#upload-progress').addClass('fade');
                        }
                    })
                    .always(function () {
                        setTimeout(function () {
                            $('#upload-progress').addClass('fade');
                            $('.bar').css('width', '0%');
                        }, 1000);
                        $('[type=submit]').removeAttr('disabled');
                    });
        }
    });
</script>